config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
  root "users#index"
  resources :users, only: [:index, :show] do
  resources :posts, only: [:index, :show, :new, :create] do
  resources :comments, only: [:new, :create]
  resources :likes, only: [:create]
end
end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_create :increment_comment_count

  def increment_comment_count
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_create :update_likes_counter

  def update_likes_counter
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :comments
  has_many :likes

  after_save :update_posts_counter

  validates :text, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def update_posts_counter
    author.increment!(:posts_counter)
  end

  def recent_comment_count
    comments.order(created_at: :desc).limit(5)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, foreign_key: :author_id
  has_many :comments, foreign_key: :author_id
  has_many :likes, foreign_key: :author_id

  validates :name, presence: true, length: { maximum: 50 }
  attribute :posts_counter, :integer, default: 0
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def return_three_most_recent_posts
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def current_user
    User.first
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
    @post = Post.find(params[:post_id])
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = current_user.comments.build(comment_params)
    @comment.post = @post
    @comment.author_id = current_user.id

    if @comment.save
      redirect_to user_post_path(current_user, params[:post_id])
    else
      render :new
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @post = params[:post_id]
    @user = current_user
    @like = Like.new(author_id: @user.id, post_id: @post)

    if @like.save
      flash[:success] = 'You liked the post.'
    else
      flash.now[:error] = 'you already liked this post.'
    end

    redirect_to user_post_path(@user.id, @post)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.where(author_id: params[:user_id])
    @user = User.find(params[:user_id])
  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.comments
    @like = Like.new
  end

  def new
    @user = current_user
    @post = Post.new
  end

  def create
    @user = current_user
    @post = current_user.posts.build(post_params)
    @post.author_id = @user.id

    if @post.save
      redirect_to user_posts_path(@user)
    else
      render :new
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @recent_posts = @user.return_three_most_recent_posts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  # helper methods for posts
end

app/helpers/user_helper.rb
module UserHelper
  # helper methods for users
end

app/views/comments/new.html.erb
<h1> create new comment</h1>

<%= form_with model: @comment, url: user_post_comments_path(@post), local: true do |form| %>
    <%= form.label :text %>
    <%= form.text_area :text %>

    <%= form.submit "Create Comment" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<div class="posts-container">
  <div class="username-holder">
    <img src="<%= @user.photo %>" alt="user photo">
    <div class="user-detail">
      <h1><%= @user.name %></h1>
      <p>Number of posts: <%= @user.posts.count %></p>
    </div>
  </div>

  <div class="posts">
    <% @posts.includes(comments:[:author]).each do |post| %>
      <div class="one-comment">
        <%= link_to user_post_path(@user, post.id) do %>
          <h2><%= post.title %></h2>
          <p><%= post.text %></p>
          <div class="comments-likes">
            <span>comments: <%= post.comments_counter %>,</span>
            <span>likes: <%= post.likes_counter %></span>
          </div>
          <div class="comments-container">
            <% post.recent_comment_count.each do |comment| %>
              <div class="single-comment">
                <span><%= comment.author.name %>  : <%= comment.text %></span>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
      <button> Pagination </button>
    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<h1>create new post</h1>

<%=form_with model: @post, url: user_posts_path(@user) do |form| %>
    <%= form.label :title %>
    <%= form.text_field :title %>

    <%= form.label :text %>
    <%= form.text_area :text %>

    <%= form.submit "Create Post" %>
<% end %>

app/views/posts/show.html.erb
<div class="comments-container">
  <div class="comment-wrapper">
    <div class="comment-head">
      <h2 class="post-title">
        <%= @post.title %> By <%= @post.author.name %>
      </h2>
      <div class="comments-likes">
        <span>Comments: <%= @post.comments_counter %>,</span>
        <span>Likes: <%= @post.likes_counter %></span>
      </div>
    </div>

    <p><%= @post.text %></p>
  </div>

  <div class="like-form">
    <h2>Leave a like</h2>
    <%= form_with model: @like, url: user_post_likes_path(@post.author, @post), scope: :like do |form| %>
      <%= form.submit 'Like', class: 'like-button' %>
    <% end %>
    <button type="button" class="like-button">
      <%= link_to "Comment", new_user_post_comment_path(post_id: @post.id), { class: "comment-link" } %>
    </button>
  </div>

  <div class="comments">
    <% @comments.each do |comment| %>
      <div class="single-comment">
        <span><%= comment.author.name %> : <%= comment.text %></span>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <h2>Users</h2>
  <% @users.each do |user| %>
    <%= link_to user_path(user) do %>
      <div class="user-list">
        <img src="<%= user.photo %>" alt="user photo">
        <div class="description">
          <p><%= user.name %></p>
          <p>Number of posts: <%= user.posts.count %></p>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/users/posts.html.erb
<p> Here is a list of posts by user ID </p>

app/views/users/show.html.erb
<h1>Listing users</h1>

<div class="user-info">
  <div class="user-photo">
    <%= image_tag @user.photo %>
    <div class="user-description">
    <h1><%= @user.name %></h1>
    <p>Number of posts: <%= @user.posts.count %></p>
  </div>
</div>

<div class="bio">
  <h2>Bio</h2>
  <p><%= @user.bio %></p>
</div>

<div class="user-posts">
  <% @user.posts.each do |post| %>
    <div class="one-post">
      <a href="/users/<%= @user.id %>/posts/<%= post.id %>">
        <div class="post-text">
        <p><%= post.title %></p>
          <p><%= post.text %></p>
        </div>
        <div class="post-info">
          <span>comments: <%= post.comments.count %>, likes: <%= post.likes.count %> </span>
        </div>
      </a>
    </div>
  <% end %>
  <a href="<%=@user.id%>/posts/" class="button">See all posts</a>
</div>
</div>